name: "Greet Contributor"
on:
  pull_request:
    types: [opened]

jobs:
  GreetCommitter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet contributor"
        uses: ibakshay/greet-contributors-action@v3
